### ISSUE TITLE
Convert CO2 Pilot Budget countries nc to COG.

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data#19]
# PI Objective

# Description
JPL has requested to add a country wise budget data to the CO2 budgets dataset.

>I think that it would be interesting to display the countries in addition to the gridded dataset. These data come in a separate netcdf (or csv) file. 

The fie is located in the following location, we need to convert it to a COG to be able to publish it to the catalog and then to the dashboard.
- https://drive.google.com/file/d/1ynpl3_ZZefHY_c1kESEEqljux01NxS0F/view?usp=sharing

Here's the script used to convert gridded budget datasets: https://github.com/US-GHG-Center/ghgc-docs/blob/main/cog_transformation_scripts/nasa_ceos_co2_flux_data_transformation.py, could probably reuse this with some changes to get the transformation done.

# Acceptance Criteria
- [ ] data converted to a COG
- [ ] tested that titiler can read it - via this viewer: https://staging-raster.delta-backend.com/cog/viewer

**Comment by jpolchlo** [comment]
If I'm reading the data correctly, this is not a gridded file.  How do we want to go about rasterizing the content of this file?  Am I missing something?

**Comment by slesaad** [comment]
Sorry I didn't realize that, my bad, maybe this can be vector data that can be served via https://github.com/NASA-IMPACT/veda-features-api

@smohiudd @ranchodeluxe how hard is that?

**Comment by ranchodeluxe** [comment]
Unfortunately the Fire Team thinks it would be strange to have other collections in their instance since they've been telling folks all the data in that API is related to Fire Things ™️

IMHO the next best option here is to generalize the IaC of [veda-features-api](https://github.com/NASA-IMPACT/veda-features-api) and the vector ingest in [veda-data-airflow](https://github.com/NASA-IMPACT/veda-data-airflow/tree/dev/docker_tasks/vector_ingest) to handle to handle multiple clients. More details below

### Generalize veda-features-api IaC (LOE: a few days to a week if unbothered)

Some folks might want to create another repo for this request. But that's not a sustainable pattern. I'd rather do this correctly in one repo. So the goal is to refactor the TF into reusable local modules so that we can `apply` it for different clients: think something along the lines of `terraform apply -var="client=eis-fire||veda-general"`. We'd also refactor the CI/CD to handle deploys for different clients.

0. Cross walk what Saadiq did for [GHGC features API generalization](https://github.com/US-GHG-Center/ghgc-features-api) and take the good parts. The biggest thing that has to be refactored is that the TF should be expecting to deploy into an VPC instead of declaring a standalone VPC

2. Break shared things in TF into local modules

3. Change CI/CD to deploy for multiple clients

4. All the changes above have to happen without breaking the existing site 😉 


### Generalize veda-data-airflow  (LOE: a day)

1. Basically we'd sniff the s3 URL and branch for clients based on where the data is coming from in [this section](https://github.com/NASA-IMPACT/veda-data-airflow/blob/dev/docker_tasks/vector_ingest/handler.py#L255-L264). 

2. Handle table prefixes for `load_to_featuresdb` function per client

3. Handle table prefixes for `alter_indices` function per client

**Comment by j08lue** [comment]
What is the "client" here - where we would branch out into `veda-general` and `eis-fire`?

I think in general we should not host several instances for different groups, if we can avoid it. Perhaps tagging collections or including the originating programme in the metadata could fulfil the need of a given team to show only "their" datasets?

**Comment by ranchodeluxe** [comment]
Currently groking the OGC spec for anything that deals with tenancy. But it seems slim pickings over there

**Comment by ranchodeluxe** [comment]
Here's an example of the first pattern  segmentation -- reuse of the ALB and DB via separate schemas `TIPG_DB_*` os environ variables:

http://vector2.wfs3labs.com/collections
http://vector1.wfs3labs.com/collections

Next let's see if we can get more reuse through dynamic secrets/config lookups based on domain header information 👨‍🍳

**Comment by ranchodeluxe** [comment]
Second pass of reuse here is done ✨  Still working on touch ups. But now multiple domains will reuse the API service layer as well with dynamic catalog lookups per request/response lifecycle

#### Changelog

https://github.com/developmentseed/eoapi-k8s/blob/de90b4f5ea0e8ee27206d844458a3633caf104c0/helm-chart/eoapi/eoapi-manfests-shared-services.yml

https://github.com/developmentseed/tipg/compare/main...ranchodeluxe:tipg:feature/schema_middlewares?expand=1

#### Examples

http://vector2.wfs3labs.com/collections
http://vector1.wfs3labs.com/collections

**Comment by j08lue** [comment]
Should we move the latest discussion out to a dedicated ticket, to give it better visibility / tracking?
